--- Makefile	2013-10-17 22:00:28.000000000 -0700
+++ Makefile.new	2013-10-17 22:18:19.000000000 -0700
@@ -47,13 +47,14 @@
 
 openfst-1.3.2/Makefile: openfst-1.3.2/.patched
 		cd openfst-1.3.2/; \
-		./configure --prefix=`pwd` --enable-static --enable-shared --enable-far --enable-ngram-fsts
+		./configure --prefix=`pwd` --enable-static --enable-shared --enable-far --enable-ngram-fsts CXX=g++-4.8
 
 
 .PHONY: openfst-1.3.2/.patched
 openfst-1.3.2/.patched: | openfst-1.3.2_tgt
 		-cd openfst-1.3.2/src/include/fst; \
-		patch -p0 -N < ../../../../openfst.patch;
+		patch -p0 -N < ../../../../openfst.patch; \
+		patch -p0 -N < ../../../../openfst.patch.2;
 		touch $@ 	
 
 openfst-1.3.2_tgt: openfst-1.3.2.tar.gz
@@ -75,6 +76,7 @@
 .PHONY: sctk_patched
 sctk_patched: | sctk-2.4.0
 		cd sctk-2.4.0/; \
+		patch -p0 -N < ../sctk.patch; \
 		for x in src/asclite/core/recording.h src/asclite/core/recording.cpp; do \
 			sed 's/Filter::Filter/::Filter/' $$x > tmpf; mv tmpf $$x; \
 		done;
@@ -96,16 +98,18 @@
 irstlm/Makefile: irstlm/.patched
 		cd irstlm; \
 		(./regenerate-makefiles.sh || ./regenerate-makefiles.sh) && \
-		./configure --prefix `pwd` 
+		./configure --prefix `pwd` CXX=g++-4.8
 
 
 irstlm/.patched: | irstlm
 		-cd irstlm;\
-		patch --verbose -N -p0 < ../interpolatedwrite-5.60.02.patch
+		patch --verbose -N -p0 < ../interpolatedwrite-5.60.02.patch; \
+		patch --verbose -N -p0 < ../irstlm.patch; \
+		mv configure.in configure.ac
 		touch $@ 		
 
 irstlm:
-		svn -r 398 co https://svn.code.sf.net/p/irstlm/code/trunk irstlm
+		svn -r 398 co --non-interactive --trust-server-cert https://svn.code.sf.net/p/irstlm/code/trunk irstlm
 
 atlas: ATLAS/include/cblas.h
 
